# Generated by Django 2.2 on 2019-04-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('imgUrl', models.URLField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
